# Site settings
title: James D. Mosier
email: james@jamesdmosier.com
description: "James Mosier is a web developer & software engineer from Akron Ohio. He specializes in front-end development (JavaScript!), C# (ASP.NET) along with HTML5, CSS3, Xamarin for mobile development, & a ton more."
# baseurl: "http://jamesdmosier.com"
# url: "http://jamesdmosier.com"
baseurl: "http://192.168.1.143:3001"
url: "http://192.168.1.143:3001"

# Build settings
markdown: kramdown
permalink: pretty

#https://github.com/jekyll/jekyll-redirect-from
gems:
  - jekyll-redirect-from

#Exclude
exclude: ['CNAME', 'node_modules', '.bowerrc', '.gitignore', 'sass', 'bower.json', 'package.json', 'Gruntfile.js', 'lib/jquery/src', '.sass-cache']

