# Site settings
title: James D. Mosier
email: james@jamesdmosier.com
description: "James Mosier is a web developer + software engineer from Akron Ohio. He specializes in C#, ASP.NET, JavaScript, CSS, jQuery, Xamarin, AngularJS, and open source projects (on Github!)."
baseurl: "http://jamesdmosier.com"
url: "http://jamesdmosier.com"

# Build settings
markdown: kramdown
permalink: pretty

#Exclude
exclude: ['node_modules', 'sass', 'README.md', 'bower.json', 'package.json', 'Gruntfile.js']

